	const spellData =  {
		"Acid Splash": {
			college: "Conjuration",
			subschool: "Creation",
			descriptor: ["Acid"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: "Close",
			duration: "Instantaneous",
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Alarm": {
			college: "Abjuration",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			focusComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Close",
			duration: 7200,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true,
			canBeWiden: true
		},
		"Animate Rope": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			duration: 6,
			durationIsPerLevel: true,
			range: "Medium",
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Arcane Mark": {
			college: "Universal",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			duration: "Permanent",
			range: 0,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Bane": {
			college: "Enchantment",
			subschool: "Compulsion",
			descriptor: ["Fear", "Mind-Affecting"],
			spellResistance: true,
			harmless: false,
			object: false,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			duration: 60,
			durationIsPerLevel: true,
			empowerable: false,
			range: 50,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Bless": {
			college: "Enchantment",
			subschool: "Compulsion",
			descriptor: ["Mind-Affecting"],
			spellResistance: true,
			harmless: true,
			object: false,
			duration: 60,
			durationIsPerLevel: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: 50,
			hasSavingThrow: true,
			canBeQuicken: true,
			areaType: "Burst"
		},
		"Bless Water": {
			college: "Transmutation",
			descriptor: ["Good"],
			spellResistance: true,
			harmless: false,
			object: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			duration: "Instantaneous",
			materialComponentCost: 2500,
			empowerable: false,
			range: "Touch",
			hasSavingThrow: true,
			canBeQuicken: false
		},
		"Burning Hands": {
			college: "Evocation",
			descriptor: ["Fire"],
			spellResistance: true,
			harmless: false,
			object: false,
			verbalComponent: true,
			somaticComponent: true,
			duration: "Instantaneous",
			empowerable: true,
			range: 15,
			hasSavingThrow: true,
			canBeQuicken: true,
			canBeWiden: true
		},
		"Calm Animals": {
			college: "Enchantment",
			subschool: "Compulsion",
			descriptor: ["Mind-Affecting"],
			spellResistance: true,
			harmless: false,
			object: false,
			verbalComponent: true,
			somaticComponent: true,
			duration: 60,
			durationIsPerLevel: true,
			empowerable: true,
			range: "Close",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Cause Fear": {
			college: "Necromacy",
			descriptor: ["Fear", "Mind-Affecting"],
			spellResistance: true,
			harmless: false,
			object: false,
			verbalComponent: true,
			somaticComponent: true,
			duration: 6,
			durationMax: 24,
			empowerable: false,
			range: "Close",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Charm Animal": {
			college: "Enchantment",
			subschool: "Charm",
			descriptor: ["Mind-Affecting"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			duration: 3600,
			durationIsPerLevel: true,
			empowerable: false,
			range: "Close",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Charm Person": {
			college: "Enchantment",
			subschool: "Charm",
			descriptor: ["Mind-Affecting"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			duration: 3600,
			durationIsPerLevel: true,
			empowerable: false,
			range: "Close",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Chill Touch": {
			college: "Necromacy",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			duration: "Instantaneous",
			range: "Touch",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Color Spray": {
			college: "Illusion",
			subschool: "Pattern",
			descriptor: ["Mind-Affecting"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: true,
			duration: "Instantaneous",
			range: 15,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Command": {
			college: "Enchantment",
			subschool: "Compulsion",
			descriptor: ["Language-Dependent", "Mind-Affecting"],
			spellResistance: true,
			verbalComponent: true,
			empowerable: false,
			range: "Close",
			duration: 6,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Comprehend Languages": {
			college: "Divination",
			descriptor: [],
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			divineFocusComponent: true,
			empowerable: false,
			range: "Personal",
			duration: 600,
			durationIsPerLevel: true,
			canBeQuicken: true
		},
		"Create Water": {
			college: "Conjuration",
			subschool: "Creation",
			descriptor: ["Water"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Close",
			duration: "Instantaneous",
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Cure Light Wounds": {
			college: "Conjuration",
			subschool: "Healing",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: "Touch",
			duration: "Instantaneous",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Cure Minor Wounds": {
			college: "Conjuration",
			subschool: "Healing",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Touch",
			duration: "Instantaneous",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Curse Water": {
			college: "Necromacy",
			descriptor: ["Evil"],
			spellResistance: true,
			object: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 2500,
			empowerable: false,
			range: "Touch",
			duration: "Instantaneous",
			hasSavingThrow: true,
			canBeQuicken: false
		},
		"Dancing Lights": {
			college: "Evocation",
			descriptor: ["Light"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Medium",
			duration: 60,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Daze": {
			college: "Enchantment",
			subschool: "Compulsion",
			descriptor: ["Mind-Affecting"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Close",
			duration: 6,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Deathwatch": {
			college: "Necromacy",
			descriptor: ["Evil"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: 30,
			duration: 600,
			durationIsPerLevel: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Detect Animals or Plants": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Long",
			duration: 600,
			durationRequiresConcentration: true ,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Detect Chaos": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: true,
			range: 60,
			duration: 600,
			durationRequiresConcentration: true,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Detect Evil": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: true,
			range: 60,
			duration: 600,
			durationRequiresConcentration: true,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Detect Good": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: true,
			range: 60,
			duration: 600,
			durationRequiresConcentration: true,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Detect Law": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: true,
			range: 60,
			duration: 600,
			durationRequiresConcentration: true,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Detect Magic": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: 60,
			duration: 60,
			durationRequiresConcentration: true,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Detect Poison": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Close",
			duration: "Instantaneous",
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Detect Secret Doors": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: 60,
			duration: 60,
			durationRequiresConcentration: true,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Detect Snares and Pits": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: 60,
			duration: 600,
			durationRequiresConcentration: true,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Detect Undead": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			divineFocusComponent: true,
			empowerable: true,
			range: 60,
			duration: 60,
			durationIsPerLevel: true,
			durationRequiresConcentration: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Disguise Self": {
			college: "Illusion",
			subschool: "Glamer",
			descriptor: [],
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Personal",
			duration: 600,
			durationIsPerLevel: true,
			dismissible: true,
			canBeQuicken: true
		},
		"Disrupt Undead": {
			college: "Necromacy",
			descriptor: [],
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: "Close",
			duration: "Instantaneous",
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Divine Favor": {
			college: "Evocation",
			descriptor: [],
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Personal",
			duration: 60,
			canBeQuicken: true
		},
		"Doom": {
			college: "Necromacy",
			descriptor: ["Fear", "Mind-Affecting"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Medium",
			duration: 60,
			durationIsPerLevel: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Endure Elements": {
			college: "Abjuration",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 86400,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Enlarge Person": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Close",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Entangle": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Long",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true,
			canBeWiden: true
		},
		"Entropic Shield": {
			college: "Abjuration",
			descriptor: [],
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Personal",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			canBeQuicken: true
		},
		"Erase": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Close",
			duration: "Instantaneous",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Expeditious Retreat": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Personal",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			canBeQuicken: true
		},
		"Faerie Fire": {
			college: "Evocation",
			descriptor: ["Light"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Long",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true,
			canBeWiden: true
		},
		"Feather Fall": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			object: true,
			verbalComponent: true,
			empowerable: false,
			range: "Close",
			hasSavingThrow: true,
			canBeQuicken: false
		},
		"Flare": {
			college: "Evocation",
			descriptor: ["Light"],
			spellResistance: true,
			verbalComponent: true,
			empowerable: false,
			range: "Close",
			duration: "Instantaneous",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Ghost Sound": {
			college: "Illusion",
			subschool: "Figment",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Close",
			duration: 6,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Goodberry": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: true,
			range: "Touch",
			duration: 86400,
			durationIsPerLevel: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Grease": {
			college: "Conjuration",
			subschool: "Creation",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Close",
			duration: 6,
			durationIsPerLevel: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Guidance": {
			college: "Divination",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 60,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Hide from Animals": {
			college: "Abjuration",
			descriptor: [],
			spellResistance: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 600,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Hide from Undead": {
			college: "Abjuration",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 600,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Hold Portal": {
			college: "Abjuration",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			empowerable: false,
			range: "Medium",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true 
		},
		"Hypnotism": {
			college: "Enchantment",
			subschool: "Compulsion",
			descriptor: ["Mind-Affecting"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: "Close",
			duration: 12,
			durationMax: 48,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Identify": {
			college: "Divination",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 10000,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: "Instantaneous",
			hasSavingThrow: false,
			canBeQuicken: false
		},
		"Inflict Light Wounds": {
			college: "Necromancy",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: "Touch",
			duration: "Instantaneous",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Inflict Minor Wounds": {
			college: "Necromacy",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Touch",
			duration: "Instantaneous",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Jump": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Touch",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Know Direction": {
			college: "Divination",
			descriptor: [],
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Personal",
			duration: "Instantaneous",
			canBeQuicken: true
		},
		"Light": {
			college: "Evocation",
			descriptor: ["Light"],
			spellResistance: false,
			verbalComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 600,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Longstrider": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Personal",
			duration: 3600,
			durationIsPerLevel: true,
			dismissible: true,
			canBeQuicken: true
		},
		"Lullaby": {
			college: "Enchantment",
			subschool: "Compulsion",
			descriptor: ["Mind-Affecting"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Medium",
			duration: 6,
			durationIsPerLevel: true,
			durationBoostedByConcentration: true,
			hasSavingThrow: true,
			canBeQuicken: true,
			canBeWiden: true
		},
		"Mage Armor": {
			college: "Conjuration",
			subschool: "Creation",
			descriptor: ["Force"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			focusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 3600,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Mage Hand": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Mage Hand",
			duration: "Concentration",
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Magic Fang": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 60,
			durationIsPerLevel: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Magic Missile": {
			college: "Evocation",
			descriptor: "Force",
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: "Medium",
			duration: "Instantaneous",
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Magic Stone": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			object: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: true,
			range: "Touch",
			duration: 1800,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Magic Weapon": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			object: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 60,
			durationIsPerLevel: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Mending": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			object: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: 10,
			duration: "Instantaneous",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Message": {
			college: "Transmutation",
			descriptor: ["Language-Dependent"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			focusComponent: true,
			empowerable: false,
			range: "Medium",
			duration: "600",
			durationIsPerLevel: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Mount": {
			college: "Conjuration",
			subschool: "Summoning",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Close",
			duration: 7200,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Nystul's Magic Aura": {
			college: "Illusion",
			subschool: "Glamer",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			focusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 86400,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Obscuring Mist": {
			college: "Conjuration",
			subschool: "Creation",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: 20,
			duration: 60,
			durationIsPerLevel: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Open/Close": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			object: true,
			verbalComponent: true,
			somaticComponent: true,
			focusComponent: true,
			empowerable: false,
			range: "Close",
			duration: "Instantaneous",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Pass without Trace": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 3600,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Prestidigitation": {
			college: "Universal",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: 10,
			duration: 3600,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Produce Flame": {
			college: "Evocation",
			descriptor: ["Fire"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: 0,
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Protection from Chaos": {
			college: "Abjuration",
			descriptor: ["Lawful"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow:true,
			canBeQuicken: true
		},
		"Protection from Evil": {
			college: "Abjuration",
			descriptor: ["Good"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Protection from Good": {
			college: "Abjuration",
			descriptor: ["Evil"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Protection from Law": {
			college: "Abjuration",
			descriptor: ["Chaotic"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Purify Food and Drink": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			object: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: 10,
			duration: "Instantaneous",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Ray of Enfeeblement": {
			college: "Necromacy",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: "Close",
			duration: 60,
			durationIsPerLevel: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Ray of Frost": {
			college: "Evocation",
			descriptor: ["Cold"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: "Close",
			duration: "Instantaneous",
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Read Magic": {
			college: "Divination",
			descriptor: [],
			verbalComponent: true,
			somaticComponent: true,
			focusComponent: true,
			empowerable: false,
			range: "Personal",
			duration: 600,
			durationIsPerLevel: true,
			canBeQuicken: true
		},
		"Reduce Person": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0, 
			empowerable: false,
			range: "Close",
			duration: 3600,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Remove Fear": {
			college: "Abjuration",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Close",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Resistance": {
			college: "Abjuration",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 60,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Sanctuary": {
			college: "Abjuration",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 6,
			durationIsPerLevel: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Shield": {
			college: "Abjuration",
			descriptor: ["Force"],
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Personal",
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Shield of Faith": {
			college: "Abjuration",
			descriptor: [],
			spellResistance: true,
			harmless: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Touch",
			duration: 60,
			durationIsPerLevel: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Shillelagh": {
			college: "Transmutation",
			descriptor: [],
			spellResistance: true,
			object: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: true,
			range: "Touch",
			duration: 60,
			durationIsPerLevel: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Shocking Grasp": {
			college: "Evocation",
			descriptor: ["Electricity"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: true,
			range: "Touch",
			duration: "Instantaneous",
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Silent Image": {
			college: "Illusion",
			descriptor: ["Figment"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			focusComponent: true,
			empowerable: false,
			range: "Long",
			duration: "Concentration",
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Sleep": {
			college: "Enchantment",
			subschool: "Compulsion",
			descriptor: ["Mind-Affecting"],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Medium",
			duration: 60,
			durationIsPerLevel: true,
			hasSavingThrow: true,
			canBeQuicken: true,
			canBeWiden: true
		},
		"Speak with Animals": {
			college: "Divination",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Personal",
			duration: 60,
			durationIsPerLevel: true,
			canBeQuicken: true
		},
		"Summon Instrument": {
			college: "Conjuration",
			subschool: "Summoning",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: 0,
			duration: 60,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Summon Monster I": {
			college: "Conjuration",
			subschool: "Summoning",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			focusComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Close",
			duration: 6,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Summon Nature's Ally I": {
			college: "Conjuration",
			subschool: "Summoning",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Close",
			duration: 6,
			durationIsPerLevel: true,
			dismissible: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Tenser's Floating Disk": {
			college: "Evocation",
			descriptor: ["Force"],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Close",
			duration: 3600,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Touch of Fatigue": {
			college: "Necromacy",
			descriptor: [],
			spellResistance: true,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Touch",
			duration: 600,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"True Strike": {
			college: "Divination",
			descriptor: [],
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Personal",
			duration: "See text",
			canBeQuicken: true
		},
		"Unseen Servant": {
			college: "Conjuration",
			subschool: "Creation",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			materialComponent: true,
			materialComponentCost: 0,
			empowerable: false,
			range: "Close",
			duration: 3600,
			durationIsPerLevel: true,
			hasSavingThrow: false,
			canBeQuicken: true
		},
		"Ventriloquism": {
			college: "Illusion",
			subschool: "Figment",
			descriptor: [],
			spellResistance: false,
			verbalComponent: true,
			somaticComponent: true,
			empowerable: false,
			range: "Close",
			duration: 60,
			durationIsPerLevel: true,
			hasSavingThrow: true,
			canBeQuicken: true
		},
		"Virtue": {
			college: "Transmutation",
			descriptor:  [],
			spellResistance: true,
			harmless: true,
			verbalComponent: true,
			somaticComponent: true,
			divineFocusComponent: true,
			empowerable: false,
			range: "Touch",
			duration: 60,
			hasSavingThrow: true,
			canBeQuicken: true
		}
	}
